### ISSUE TITLE
Create build action

### ISSUE THREAD

**Issue by wylie39** [themoonisacheese/2bored2wait#117]
If you guys want I can create a github action that runs npm install and then tests the app to make sure it doesn't crash. I can write it but I think someone else will have to deploy it, because I don't have the permissions.

**Comment by MrGeorgen** [comment]
Good idea. Do you only want to test the initial startup or also connecting to a server, client connecting to 2b2w ...

**Comment by wylie39** [comment]
Its going to run npm install then npm start then a test function I have to add to the code.

**Comment by wylie39** [comment]
@themoonisacheese Do you Kno how to set up github actions? If not would it be possible to get the correct permissions so I can set them up?

**Comment by themoonisacheese** [comment]
reopening because this issue should serve as "build action discussion central".
the current action seems to work properly (it obviously returns "no config file" but it's a fantastic start) but it doesn't seem to trigger on PRs despite PRs being mentionned in the config file. unsure why that is, it might be due to the fact that all current open PRs are older than the action itself.

it might be worth trying to open a dummy PR just to test things.

**Comment by wylie39** [comment]
Just ran a test PR and it works fine.

**Comment by MrGeorgen** [comment]
basing testing is done
