### ISSUE TITLE
Player that was connected before 2b2w doesn't appear.

### ISSUE THREAD

**Issue by HyCore** [themoonisacheese/2bored2wait#148]
I notice this wierd bug, when you connect, the playerlist in the tab is empty, and you will not be able to see other player exept those who did connect after you.
My thought:

Is it possible to store and load the playerlist to make the tab normal.

+ add a command to store chunk on demand. (and store them when a player disconnect)
+ add a command to force reload the playerlist if a player doesn't appear in renderdistance
+ add a command to manually change gamemode if it's broken
+ add a commande to change the time
+ add a better antiafk (auto mine or automove a bit)

It's would be amazing if all of that is added.

**Comment by MrGeorgen** [comment]
> add a command to store chunk on demand. (and store them when a player disconnect)

I could make something that changes the chunk cache if a block update is sent. I could use some code form [here](https://github.com/Rob9315/2b2tproxy)
> add a command to manually change gamemode if it's broken

a okay workaround. If not only disconnect but also restart the client it worked one time. I don't know why the gamemode is broken because I listen gamemode changes. 2b2w could also always send survival mode to the client
> add a commande to change the time

I could try to find the right packet and send the right time to the client. I can take some Inspiration form [mcidle](https://github.com/qubard/mcidle-python)
>add a better antiafk (auto mine or automove a bit)

is possible but not that esay. I could use [mineflayer](https://github.com/PrismarineJS/mineflayer) to connect to 2b2w, move the player somehow and disconnect the bot client if the actual minecraft client connects.
>add a command to force reload the playerlist if a player doesn't appear in renderdistance

I don't think there is a tablist reload packet, you could send to the server. Again if saving the right packets and resend them would do the job. It has not a priority for me because it is not game breaking
I probably will do some things described here, but you can expect it to take some time. Contributions are always welcome

**Comment by HyCore** [comment]
Hi sure, i can try to help you, i already made some fork on my private server i could share here, but they are quiet unstable. 
Here some problem i've encounter, when a player connect in the queue, after a day or two, it broke.
I mean, when 2b2w try to reconnect after a restart for exemple (over and over again), 2b2w launch a proxy instance too soon and collide with the previous one and hardcrash telling us there is already an address in use. 
![Screenshot_144](https://user-images.githubusercontent.com/48274082/101691890-a6d9bb00-3a6f-11eb-94ae-3b2b198f87ee.png)

I tried to make a workaround with nodemon but same issue after some time it end up crashing.
I will continue to work on all of that, with some friend we setup 6 bots that builds, gather, store ressources with baritone but we are bottlenecked by 2b2w. Tho you already make an incredible job with themoonisacheese so congrats. Btw do you have discord ?
![Screenshot_89](https://user-images.githubusercontent.com/48274082/101691852-975a7200-3a6f-11eb-9ea2-d2a52928d55b.png)

**Comment by themoonisacheese** [comment]
if you would like to help, you are welcome to submit a pull request (as that's what they're for) or just explain some concepts we may not have thought about here.

all my links are available on [poggers.website](http://poggers.website). MrGoergen can give you his discord if he so wishes.

**Comment by HyCore** [comment]
Yeah sure i will add some submit but i will to quickly translate all my comment in it because there are in french so it will not be very understandable for our english mate.

Some interesting thought to fix the "adresse already in use" crash, yeah randomizing it could be a nice feature and add some security too. 
And for an other point of view we can do this:  add a function that tell if the server is ready to start himself again by making some check everywhere when the "join" and "startqueuing" function are called.
![Screenshot_145](https://user-images.githubusercontent.com/48274082/101694035-c9b99e80-3a72-11eb-859a-1e5526a503fa.png)
![Screenshot_147](https://user-images.githubusercontent.com/48274082/101694089-de963200-3a72-11eb-867d-2c378b4dd977.png)

 I need to work on some EventEmitter to make it work but im not sure if it will work.
![Screenshot_146](https://user-images.githubusercontent.com/48274082/101694050-d0e0ac80-3a72-11eb-9854-923a99015011.png)

**Comment by MrGeorgen** [comment]
Yeah my discord username: IAmCoronaEatMe#6725 (weird name I know, just for joke)
>And for an other point of view we can do this: add a function that tell if the server is ready to start himself again by making some check everywhere when the "join" and "startqueuing" function are called.

good approach

**Comment by MrGeorgen** [comment]
>Yeah sure i will add some submit but i will to quickly translate all my comment in it because there are in french so it will not be very understandable for our english mate.

I had french in school but I was horrible at it xd

**Comment by MrGeorgen** [comment]
we could use https://github.com/Rob9315/mcproxy as it caches packets far
better

**Comment by MrGeorgen** [comment]
mostly done expect the anti-afk
