### ISSUE TITLE
seemingly un-used branch

### ISSUE THREAD

**Issue by AverageComet250** [themoonisacheese/2bored2wait#181]
is the dev branch still in use or does it need to be removed.

if it's now un-needed it should be merged into master, right?

**Comment by MrGeorgen** [comment]
It is un-needed but it won't get merged into master because it caches almost all packets and resents them after the client reconnects. This is a bad because it can easily be gigabytes of data. The most important packets are already cached, resent and deleted, if not needed anymore, in the master branch
