### ISSUE TITLE
[Suggestion] Instead of a proxy server, make the program hand everything to your client when the queue ends

### ISSUE THREAD

**Issue by cyruscook** [themoonisacheese/2bored2wait#22]
Difficult to explain.

At the moment, the program works by being a proxy server, which is good, but also means that there is extra latency (especially if your running it off an external device) and caveats such as having disconnecting from the proxy not disconnect from your client.

Why not pass over the login key and the server connection hook to the client. I hope that explains it? Not sure how feasible it would be but it would definitely be an improvement.

**Comment by themoonisacheese** [comment]
when a client of any kind makes an outgoing connection to a server, the servers port is fixed, but the clients port is not. it is unchanging during each connection, yes, but once the connection is closed it can change however it wants. i'm pretty sure that nowadays, clients no longer choose their ports themselves and instead get provided one by the operating system. this means that no matter what I do, unless i was willing to mod windows (probably linux if I were to actually do this), there's no way your idea can be implemented while not integrating the proxy to the minecraft client (which i'm not doing because that would prevent you from using hacked clients)
