### ISSUE TITLE
Vps

### ISSUE THREAD

**Issue by Ghostinfinit** [themoonisacheese/2bored2wait#230]
This is crazy but do you think there is a way to run this on a vps. If you think you know how reply.

**Comment by ChillerDragon** [comment]
Sure I do not see how it differs from your local machine.

**Comment by czho** [comment]
With docker, it's even easier. I would suggest Linode because they are cheap(around $5 a month on the lowest tier) and easy to setup. Note you should probably run 2b2w with whitelist enabled because someone with an IP scraper could just see that there is a 2b2w instance running on the server's IP and login to 2b2w without you being able to know. This is even worse because if you are already logged on you won't be able to tell someone else logged on, the server will just stop responding as it is handling all the packets thru the new account the just logged in.

**Comment by czho** [comment]
Well thats just for controlling it thru the web, in config there is an option to turn on whitelisting to make it so only you can only join the 2b2w server. Whitelisting just makes it so the account using 2b2w is the same account logging into the server, with whitelisting the server is in online mode so you would have to have someone's Minecraft password already to log on to the 2b2w server.

**Comment by MrGeorgen** [comment]
see #10 to protect you from a man in the middle stealing you password

**Comment by soham9229** [comment]
I am using replit.com to host it. Can anyone help me with hosting it . 
I tried this doing before and was successful in joining the queue by running 2b2w on replit. But I dont know what IP should i put to actually get into game from my instance.
