### ISSUE TITLE
Npm error

### ISSUE THREAD

**Issue by 000-whoami-000** [themoonisacheese/2bored2wait#244]
C:\Users\reeng\Downloads\2bored2wait-master\main.js:26
        throw("error loading config file:\n" + err);
        ^
error loading config file:
SyntaxError: Unexpected token D in JSON at position 14
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! 2bored2wait@1.0.0 start: `node main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the 2bored2wait@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\reeng\AppData\Roaming\npm-cache\_logs\2021-04-04T09_39_30_761Z-debug.log

**Comment by LikeableMoneky** [comment]
Please Reply if you know how to fix this, i also have the same problem. Thanks.

**Comment by MrGeorgen** [comment]
invalid json syntax

**Comment by LikeableMoneky** [comment]
How do we fix this invalid json syntax, or is it something you have fix and we have to just wait. Thanks.

**Comment by MrGeorgen** [comment]
the syntax in your config.json is not correct. Make sure you replaced all
values as the readme says. If it still does not work check that all quotes are
closed. You can look up the json syntax online. Please that the comments are
no problem although comments are normally not allowed in json.

I'll change the error message to text above because others opened issues about
the same problem. that's also why I have only given such a short answer obove
