### ISSUE TITLE
Proxy caching

### ISSUE THREAD

**Issue by etiaro** [themoonisacheese/2bored2wait#275]
You have written in readme that entities and inventory are not cached, but I tested it and they're visible. Also, Do you have any idea where is blank texture bug coming from?

**Comment by MrGeorgen** [comment]
>You have written in readme that entities and inventory are not cached, but I tested it and they're visible.

right, thats outdated

>Also, Do you have any idea where is blank texture bug coming from?

No, this problem already exsisted with my packet caching implementation before we
switched to mcproxy

**Comment by etiaro** [comment]
Okay, but i am experiencing this on current version. Also, on much loaded chunks (like nether, 2b spawn) some od chunks arę getting shifted down on Y axis(reconnecting doesnt change anything). That's really weird. Can it be caused by really bad CPU? I am hosting 2b2w 24/7 on raspberry pi.

**Comment by rob9315** [comment]
@etiaro that seems really weird, it is probably a problem with my project mcproxy, that is now being used with 2bored2wait...
Please open an issue over [here](https://github.com/rob9315/mcproxy/issues) if you maybe have more information.
The blank texture is because with the usage of mcproxy, 2bored2wait has become more than a man-in-the-middle program

**Comment by etiaro** [comment]
Okey, waiting here: https://github.com/rob9315/mcproxy/issues/14

**Comment by rob9315** [comment]
fixed in latest mcproxy release
