### ISSUE TITLE
Feature request: log chat messages to a file & forward whispers to Discord

### ISSUE THREAD

**Issue by Hiiva** [themoonisacheese/2bored2wait#328]

**Comment by cristiioan** [comment]
Idk about whisphers but we can send all the message to discord. And log is easy to make.

**Comment by KozmikNano** [comment]
This should be a feature! Hear me out I have a good reason! So the server chat is basically a place for people to spam or chat but mostly spam now because of the discord‘s terms of service you could keep your account disabled for participating in the server of which you have your discord bot. With that in mind it will also take up a lot of your resources so if you have the server on your computer that you’re playing 2b2t on then it will slow it down by a lot.

**Comment by cristiioan** [comment]
For this we can code an anti spam. Can be a bot account be terminated due to spam?

**Comment by KozmikNano** [comment]
Maybe not the bot but the owner or the users on the server or dms

**Comment by rob9315** [comment]
> Can be a bot account be terminated due to spam?

No, it cannot. If someone cares to implement this toggleably by a config option it will definitely be merged

**Comment by Spritzerland** [comment]
@KozmikNano wait why are you here? youre supposed to be making the vpn

**Comment by rob9315** [comment]
@Spritzerland i'm sorry, but what are you contributing to this conversation? this is an issue for a feature request.
please refrain from cluttering this issue, mr. "html hacker".
what kozmik does with his time is up to him, it is quite clear what he is doing here, so, politely, please fuck off

**Comment by Spritzerland** [comment]
dude, i was just saying hi to him, cause i've seen him before
About the issue, logging chat messages to file is a good idea, discord isn't. Save whispers to seperate file, notify in terminal
