### ISSUE TITLE
Cool/Possible Idea?

### ISSUE THREAD

**Issue by sfxworks** [themoonisacheese/2bored2wait#37]
I make Kubernetes Job containers that run this and give people a unique random SRV record for 2b3t and other que servers. 

Would it be possible to put this on a remote server running nodejs and connect to it instead of localhost? I'd imagine a bit of lag unless the server was right next to 2b2t's, but seems like a cool idea. 

If so I can provide a PR / endpoint later on.

**Comment by themoonisacheese** [comment]
yeah you can totally do that. just have to open the right ports.
the problem with doing that as a service is that people have to give you their credentials which is stupid.
lag isn't really a problem because 2b2t already lags like crazy, especially in EU so adding 100ms isn't that much of a problem.

**Comment by sfxworks** [comment]
Ah, I see how that could be a trust issue yeah. A while ago I had a site that used mc logins for LGM's server that worked with Mojang's Yggdrasil. People didn't mind for that but true they might mind for something like this with their base at stake and such.
