### ISSUE TITLE
1.18.2 doesn't work

### ISSUE THREAD

**Issue by zip6como** [themoonisacheese/2bored2wait#473]
as you migth know 2b2t is on 1.12.2 but it allows you to join with versions aboth it.
i changed the config file from 1.12.2 to 1.18.2 to joinn with that vesrion but i only get an error.
if i try to join with 1.12.2 and then it works fine but 1.18.2 does not.
please fix this i would loveto use 2b2w with 1.18.2.

**Comment by zip6como** [comment]
![Screenshot 2022-08-07 140308](https://user-images.githubusercontent.com/79743601/183490084-534a3f29-0e9b-4663-aa45-3cce989f9b57.png)
here is the error message

**Comment by KozmikNano** [comment]
Only compatible with 1.12.2

**Comment by zip6como** [comment]
will it update to 1.18.2 soon?

**Comment by KozmikNano** [comment]
Not unless 2b2t updates

**Comment by themoonisacheese** [comment]
2b2w does whacky and uncharacteristic stuff with packets that are tailored specifically to 1.12. updating to 1.18 would mean rewriting half the codebase (for example, the tab-parser is pre 1.16) with no end in sight as new versions come out, all for the purpose of not having to restart minecraft to play 2b2t. 2b2w has a version in the config file because it was originally possible to just change it and be done with it, but this hasn't been the case for a long time and supporting it is nontrivial.

that said, if it can be demonstrated that newer versions offer interesting protocol changes, it is good to know that using that version's protocol against 2b2t can be done.

**Comment by zip6como** [comment]
okay

**Comment by KozmikNano** [comment]
> 2b2w does whacky and uncharacteristic stuff with packets that are tailored specifically to 1.12. updating to 1.18 would mean rewriting half the codebase (for example, the tab-parser is pre 1.16) with no end in sight as new versions come out, all for the purpose of not having to restart minecraft to play 2b2t. 2b2w has a version in the config file because it was originally possible to just change it and be done with it, but this hasn't been the case for a long time and supporting it is nontrivial.
> 
> that said, if it can be demonstrated that newer versions offer interesting protocol changes, it is good to know that using that version's protocol against 2b2t can be done.

I believe I know what changes to do in order to update but I couldn’t be bothered to update unless it’s required. Mostly because school is in session and I have no time 😀
