### ISSUE TITLE
Seems unsafe

### ISSUE THREAD

**Issue by OmriOn** [themoonisacheese/2bored2wait#475]
Why do you not use the microsoft account prompt for login? (like lunar client) it seems very suspicous that the program asks for your password and email..

**Comment by KozmikNano** [comment]
what do you mean it doesn’t ask?

**Comment by rob9315** [comment]
@OmriOn
first off, if you leave your password blank it gives you an auth link with which you can authenticate in browser.
secondly, it's all free and open source software. feel free to read through the source code to make sure nobody is stealing your credentials.

lastly, microsoft authentication is simply bad and overcomplicated. a small project like this would only consist of authentication code if it weren't for libraries like prismarinejs to do the heavy lifting. lunar client is very different because it isn't something new built from the ground up, it can simply use existing authlib code.
