### ISSUE TITLE
Not working on macOS

### ISSUE THREAD

**Issue by AustinBoath** [themoonisacheese/2bored2wait#488]
The macOS version has no file format, therefore I can't open it. I ran it in terminal, opened it in textedit. it's just a file with no format. How do I run it?

**Comment by rob9315** [comment]
as with all unix-based systems, executable files don't have to have a specific file extension. they are elf files though, as defined by their contents.
you run these files by opening a terminal and running `/path/to/executable`.
the file might not have the permissions to be executable yet, this is fixed by running `chmod +x /path/to/file`.
