### ISSUE TITLE
Stop providing binaries

### ISSUE THREAD

**Issue by sa6ta6ni6c** [themoonisacheese/2bored2wait#507]
Binaries are buggy, and seem less secure. Let people run 2bored2wait from source.

**Comment by nickcat325** [comment]
Releasing binaries does not stop people from running 2b2w from source. Also you could just say the binaries are faulty.

**Comment by themoonisacheese** [comment]
I agree that binaries have been fucked for pretty much ever. unfortunately, @sa6ta6ni6c seems to overestimate the ability of the average 2b2t player to run this from source. running from source used to be the way to use 2b2w, but many issues arised from user error. 

packaging binaries is the most effective way to provide accessible and runnable builds for windows users. linux users are probably better off running from source since they are inherently more tinker-oriented. that being said, it is evident that binaries should be more functionnal (and tests should probably be written and ran), with less friction. this has been an issue, probably due to the nexe version used, but unfortunately changing versions is unlikely to happen and last i checked nexe 3 was still in beta.

the option of a docker container exists (and as far as i can tell actually works seamlessly), but users familiar with docker will quickly see that docker is overkill as far as running a 3 file js project goes.

i have had on my mind to reimplement 2b2w in rust for quite some time, allowing for cross-platform actually-native binaries that should be better, but i haven't had the time nor drive to go through with it.

**Comment by sa6ta6ni6c** [comment]
Thanks for explanation!

Ср, 26 окт. 2022 г. в 22:41, themoonisacheese ***@***.***>:

**Comment by AntiCheap** [comment]
Please just make a guide on how you run the code from source it's not rocket science. People do what's in the readme.

**Comment by Ten2O** [comment]
Yes, a guide as to how to run from source would be great.

**Comment by KozmikNano** [comment]
> Yes, a guide as to how to run from source would be great.

There is one on the readme and one on my YouTube channel
