### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jacobjake1** [themoonisacheese/2bored2wait#549]
The ability to add multiple accounts and run them all off a single proxy would be ideal.

My idea is this: queue 10 accounts all at once, so you can connect to the proxy server at any time and select any account you wish to play on (like a middleman server almost?), and once you make your selection it sends you to the main server on that account, or if the account isn't ready yet it displays its ETA in-game or via Discord

**Comment by rob9315** [comment]
this is currently impossible due to the way the used library works under the hood. you can "recreate" the effect by having multiple instances of the proxy running at the same time. they do need different config files in that case, and for that i'd refer you to the [config-js documentation](https://github.com/node-config/node-config) which explains how to use different config files by setting environment variables
