### ISSUE TITLE
[Request] proxy sided modifications

### ISSUE THREAD

**Issue by jacobjake1** [themoonisacheese/2bored2wait#554]
I am trying to find a way to disable/spoof/remove things when connecting through the proxy, I know this is a bit of a bigger project, but this would make a base unfindable;  

I want to disable client-sided features when connecting through the proxy, such as disabling biome blending, disable slime chunks, spoofing coordinates into the tens of millions, showing the bedrock pattern of the spoofed/fake cords show or just disable bedrock entirely, and no weather like rain.

**Comment by themoonisacheese** [comment]
Hey so fun fact about that: 2b2w actually started because I was worried about getting sign banned back when that was a thing. The function FilterPacketAndSend in main.js is a remnant of where I'd unpack chunk data and remove all instances of signs from it. You would be of course unable to see signs at all but small price to pay. 

If you want to, modifying that function to add/remove (you would have to do the conversion back from the client on basically every packet) a random number (chosen at startup) from coordinates, spoofing biome info to always say plains in F3, and such is actually kind of easy (though you do get a performance hit from the chunk unpacking). Slime chunks you could strip out I guess, but the vanilla client doesn't show slime chunks beyond showing slimes when they are spawned, so maybe just don't show slime chunks with mods?

All of what you're suggesting is technically possible and even facilitated but my question is why do you want the proxy to do that? It'd be much easier in a mod.

**Comment by jacobjake1** [comment]
Hey thanks for the response,

The point of all of this is to have an unfindable base on 2b2t.

If I wanted to invite someone to the base, I would whitelist them to the proxy, they join the proxy, and can choose from a selection of accounts online (on a seperate server like a bungeecord server, think of it like a hub). If the account isn't online it shows an ETA and where it's at in the queue.

You select which account you'd like to play on and it sends you to that account on the main server.  With all of these features in place, such as what I said before, (plus I did forget one thing, block rotations), it would be impossible to find the base. (Yes I mean disable slimes, not slime chunks, I thought they showed in f3 for some reason)
