### ISSUE TITLE
Skin issue

### ISSUE THREAD

**Issue by Gl1tch64** [themoonisacheese/2bored2wait#570]
My skin is not displayed. Is there a way to solve it?

**Comment by themoonisacheese** [comment]
No.
For skins to be displayed, you would need the proxy to host an online-mode=true server, which is technically possible, but doing that means that by connecting to the proxy, you invalidate your yggdrasil token, which in turn means the proxy would need to ask for a new token to reconnect.

This would significantly increase the amount of times one needs to log in manually at minecraft.net to confirm their account isn't compromised.

Since this is local-only (other users do see your skins and theirs correctly, i suggest using a skin mod often used by cracked version players.
